### ISSUE TITLE
"No snippet model configured to use in Rich Text editor."

### ISSUE THREAD

**Issue by ubservas** [themotleyfool/wagtail-draftail-snippet#18]
I get this message in Snippet chooser modal - "No snippet model configured to use in Rich Text editor."
Ho can I configure it right way?

**Comment by andre-fuchs** [comment]
@ubservas, how did you get it running? I get the same error message in the Snippet chooser panel. I double checked my setup and cannot see the problem. Would be curious to hear how you solved it finally.

I got an `Audio` snippet in an app also named `audio`. So I added these two templates with no effect:
`audio/templates/audio/audio_snippet_link.html` and
`audio/templates/audio/audio_snippet_embed.html`

The two features are already displayed in the RichTextEditor, just the chooser panel isn’t recognizing my snippet. I tested the function `wagtail.snippets.modals.get_snippet_models()` and it lists my snippet as expected. 

Great feature to have in the RichTextEditor. Hope to get it running. Thanks for your efforts, everybody!
